---
- name: Setup host to ansible develop modules
  hosts: ubu18
  gather_facts: false

  tasks:
  - name: Clone git repo.
    git:
      repo: https://github.com/ansible/ansible.git
      dest: "$HOME/ansible"

  - name: Setup virtualenv
    shell: |
        cd $HOME/ansible
        virtualenv --prompt "(ansible)" venv

  - name: Setup pip libraries
    pip:
      requirements: "$HOME/ansible/requirements.txt"
      virtualenv: "$HOME/ansible/venv"
